### ISSUE TITLE
Blocks Absorbed by Block

### ISSUE THREAD

**Issue by nbrown983** [davidebangelista/Blocks#1]
The blocks can all be absorbed by one block. Either that, or they are stacking behind the block. This can be done with multiple blocks, and makes them unmovable.

![unnamed](https://user-images.githubusercontent.com/129208034/228311947-eea2204a-2c2b-436e-b8df-909c6cd084fc.png)

![unnamed2](https://user-images.githubusercontent.com/129208034/228311948-7df0188d-16f0-438d-83ae-cda60331db85.png)

**Comment by davidebangelista** [comment]
The UI has changed.

You now drag on order.
